version: '3'
services:
    web:
        container_name: "ppdv_dash"
        build:
            context: ./app
        environment:
            - MONGO_URL=mongodb://mongo_db:27017
#            - DATA_SOURCE_URL=http://0.0.0.0:3000/tesla/
            - DATA_SOURCE_URL=http://tesla.iem.pw.edu.pl:9080/v2/monitor/
            - ISOD_LOGIN=${ISOD_LOGIN}
            - ISOD_PASSWORD=${ISOD_PASSWORD}
            - AUTH_GROUP=${AUTH_GROUP}
            - VPN_ADDRESS=${VPN_ADDRESS}
        ports:
            - "8050:8050"
        volumes:
            - ./app:/app
        cap_add:
            - NET_ADMIN
        depends_on:
            - mongo_db

    mongo_db:
        image: mongo
        ports:
            - "27017:27017"
