version: '3'
services:
    web:
        container_name: "ppdv_dash"
        build:
            context: ./app
        environment:
            - MONGO_URL=mongodb://mongo_db:27017
            - DATA_SOURCE_URL=http://tesla.iem.pw.edu.pl:9080/v2/monitor/
        ports:
            - "8050:8050"
        volumes:
            - ./app:/app
        cap_add:
            - NET_ADMIN
        depends_on:
            - mongo_db

    mongo_db:
        image: mongo
        ports:
            - "27017:27017"
